### ISSUE TITLE
Getting TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'

### ISSUE THREAD

**Issue by GOTWIC** [kennyhml/pyinterception#8]
Here is the full error:

`(apex) C:\Users\swagn\Downloads>python test.py
Traceback (most recent call last):
  File "C:\Users\swagn\Downloads\test.py", line 1, in <module>
    import interception
  File "C:\Users\swagn\AppData\Local\Programs\Python\Python39\lib\site-packages\pyintercept-0.0.0-py3.9.egg\interception\__init__.py", line 4, in <module>
    from .inputs import *
  File "C:\Users\swagn\AppData\Local\Programs\Python\Python39\lib\site-packages\pyintercept-0.0.0-py3.9.egg\interception\inputs.py", line 6, in <module>
    from . import _utils
  File "C:\Users\swagn\AppData\Local\Programs\Python\Python39\lib\site-packages\pyintercept-0.0.0-py3.9.egg\interception\_utils.py", line 7, in <module>
    def normalize(x: int | tuple[int, int], y: Optional[int] = None) -> tuple[int, int]:
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'`

test.py just has `import interception` to test if everything has been installed properly

I installed interception, ran setup.py, and added the interception.dll to path. Any help would be appreciated!

**Comment by GOTWIC** [comment]
Seems like the issue is related to the python version. Doesn't work in 3.9, but works in 3.10. Do you think it is possible to make it work on 3.9?

**Comment by kennyhml** [comment]
Hey, thats correct, python 3.10 or higher is required to use it.

If you need to make it compatible with prior python versions, the only thing you should have to do is replace the the union operator here like `x: int | tuple[int, int]` with `x: Union[int, tuple[int, int]` and all the other places since that operator was introduced in 3.10
